name: Build VSIX

on:
  push:

env:
  PNPM_VERSION: 9
  NODE_VERSION: 22
  EXTENSION_DIR: "masm-helper"
  GRADLE_TARGET: "packageExtensionProduction"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.EXTENSION_DIR }}
    steps:
      - uses: actions/checkout@v4

      # Setup Gradle
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v4

      # Setup pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: "${{ env.EXTENSION_DIR }}"

      - name: Build
        shell: sh
        run: ./gradlew ${{ env.GRADLE_TARGET }} --no-daemon

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: masm-helper.vsix
          path: "${{ env.EXTENSION_DIR }}/build/js/packages/masm-helper-extension/dist-vsix/*.vsix"
          if-no-files-found: error
